# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.8
variables:
  DOCKER_BUILDKIT: 0

#commands to run in the Docker container before starting each job.
before_script:
  - pip install -r ./requirements.txt
  - pip install -e .
# different stages in the pipeline
stages:
  - Formatter
  - Test
formatter:
  stage: Formatter
  script:
    - pip install black
    - black --check --diff --color --line-length=100 ./
pytest:
  stage: Test
  script:
    - git clone https://oauth2:$CI_BEC_KEY@gitlab.psi.ch/bec/bec.git
    - pip install -e ./bec/bec_utils
    - pytest -v ./tests
